baseURL = "https://blog.invmy.com/Notion-Hugo-theme-Moments"
languageCode = "zh-Hans"
theme = "moments"
paginate = 20
paginatePath = '.'

[params]
    title = "Moments Demo"
    signature = "人生如逆旅，我亦是行人。"
    cover = "https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg"

    name = "Default User"
    avatar = "/img/avatar.png"

    #无限滚动
    infiniteScroll = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true