baseURL = "http://invmv.github.io/Notion-Hugo-theme-Moments/"
languageCode = "zh-Hans"
theme = "moments"
paginate = 5
paginatePath = '.'

[params]
    title = "Notion for hugo-Moments"
    signature = "Share my Life"
    cover = "https://images.unsplash.com/photo-1691157915037-68576ba139b1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    
    #无限滚动
    infiniteScroll = true